baseURL = 'https://dilokomi.moe'
languageCode = 'zh-CN'
DefaultContentLanguage = 'zh-cn'
title = 'dilokomiçš„åƒåœ¾æ¡¶'
theme = 'hugo-theme-stack'
enableEmoji = true
hasCJKLanguage = true
enableGitInfo = true
[Params.Sidebar]
compact = true
emoji = "ğŸ¥"
avatar.src = "img/1.png"
[Params.Footer]
since = 2025
customText = ""
[Params.Article]
license.enabled = true
license.default = "Licensed under CC BY 4.0"
[Params.Comments]
enabled = true
provider = "utterances"
[Params.Comments.utterances]
repo = "dilokomi/dilokomi.github.io"
