baseURL = 'https://example.org/'
languageCode = 'zh-cn'
DefaultContentLanguage = 'zh-cn'
title = 'dilokomiçš„åƒåœ¾æ¡¶'
theme = 'hugo-theme-stack'
enableEmoji = true
hasCJKLanguage = true
enableGitInfo = true
[Params.Sidebar]
compact = true
emoji = "ğŸ¥"
avatar.src = "img/-10cea75c8649c74.jpg"
[Params.Footer]
since = 2025
customText = ""
[Params.Article]
license.enabled = true
license.default = "Licensed under CC BY 4.0"
[Params.Comments.giscus]
repo = "dilokomi/dilokomi.github.io"
repoID = "R_kgDONYvflw"
category = "Announcements"
categoryID = "DIC_kwDONYvfl84Crb0Y"
mapping = "pathname"
strict = "1"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
lang = "zh-CN"
