baseURL = 'https://dilokomi.moe'
languageCode = 'zh-CN'
DefaultContentLanguage = 'zh-cn'
title = 'dilokomiçš„åƒåœ¾æ¡¶'
theme = 'hugo-theme-stack'
enableEmoji = true
hasCJKLanguage = true
enableGitInfo = true
[Params.Sidebar]
emoji = "ğŸ¥"
avatar.src = "img/1.png"
subtitle = "æˆ‘å¾ˆå¯çˆ±è¯·ç»™æˆ‘é’±"
[Params.Footer]
since = 2025
customText = ""
[Params.Article]
license.enabled = true
license.default = "Licensed under CC BY 4.0"
[Params.Comments]
enabled = true
provider = "utterances"
[Params.Comments.utterances]
repo = "dilokomi/dilokomi.github.io"
[Params.widgets]

[[Params.widgets.homepage]]
type = "search"
[[Params.widgets.homepage]]
type = "archives"
limit = 10
[[Params.widgets.homepage]]
type = "categories"
limit = 20
[[Params.widgets.homepage]]
type = "tag-cloud"
limit = 20
[[Params.widgets.page]]
type = "toc"